title: Sanjana's Website
author: Sanjana Sriram
email: sanjanasriram03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is about Sanjana Sriram to get to know her better.

# social links
twitter_username: sriram_sanjana
github_username:  Snowblue03

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
